version: "3.9"

services:
  katalogus_integration:
    build:
      context: ..
      dockerfile: nl-kat-boefjes/Dockerfile.dev
      args:
        - ENVIRONMENT=dev
    command: sh -c 'python -m pytest -v boefjes/katalogus/tests/integration'
    depends_on:
      - ci_katalogus-db
    env_file:
      - .ci/.env.test
    volumes:
    - .:/app/boefjes

  ci_katalogus-db:
    image: postgres:12.8
    env_file:
      - .ci/.env.test
