version: "3.9"

services:
  katalogus_integration:
    build:
      context: ..
      dockerfile: boefjes/Dockerfile
      args:
        - ENVIRONMENT=dev
    command: sh -c 'python -m pytest -v boefjes/katalogus/tests/integration'
    depends_on:
      - ci_katalogus-db
    env_file:
      - .ci/.env.test
    volumes:
      - .:/app/boefjes

  boefjes:
    build:
      context: ..
      dockerfile: boefjes/Dockerfile
      args:
        - ENVIRONMENT=dev
    command: sh -c 'python -m pytest -v tests'
    env_file:
      - .ci/.env.test
    volumes:
      - .:/app/boefjes

  ci_katalogus-db:
    image: postgres:15
    env_file:
      - .ci/.env.test
