version: "3.9"

services:
  ci_scheduler_unit:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    volumes:
      - .:/app/scheduler
    env_file:
      - .ci/.env.test

  ci_scheduler_integration:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    volumes:
      - .:/app/scheduler
    env_file:
      - .ci/.env.test
    depends_on:
      ci_postgres:
        condition: service_healthy
      ci_rabbitmq:
        condition: service_healthy

  ci_postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .ci/.env.test

  ci_rabbitmq:
    image: "rabbitmq:3.11-management"
    volumes:
      - ./.ci/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      retries: 4
