name: Boefjes Run the test suite

on:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "*"
    paths:
      - boefjes/**
      - octopoes/**
      - .github/workflows/boefjes_tests.yml
  pull_request:
    paths:
      - boefjes/**
      - octopoes/**
      - .github/workflows/boefjes_tests.yml

jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ubuntu-24.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
          cache: "pip" # caching pip dependencies

      - name: Install pip
        run: python3 -m pip install --upgrade pip

      - name: Install dev requirements
        run: grep -v git+https:// requirements-dev.txt | pip install -r /dev/stdin && grep git+https:// requirements-dev.txt | pip install -r /dev/stdin
        working-directory: ./boefjes

      - name: Install requirements
        run: find . -name requirements.txt | xargs -L 1 pip install -r
        working-directory: ./boefjes

      - name: Install Octopoes
        run: pip install wheel && cd octopoes && python setup.py bdist_wheel && pip install dist/octopoes*.whl

      - name: Run pytests
        run: python3 -m pytest
        working-directory: ./boefjes

      - name: Run integration tests
        run: make itest build_args='--build-arg PYTHON_VERSION=${{ matrix.version }}'
        working-directory: ./boefjes
