name: Rebuild python virtual env

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1

      - name: Replace version number with release version
        run: find . -type f -name 'version.py' -exec sed -ibak "s/__version__ = .*/__version__ = \"${RELEASE_VERSION}\"/" {} \;

      - name: prep
        run: sudo mkdir -p /var/www/html
      - name: prep chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: copy project to run location.
        run: cp -r * /var/www/html

      - name: Create env
        run: python3.8 -m venv /var/www/html/.venv

      - name: Install requirements
        run: cd /var/www/html; source .venv/bin/activate; pip install --upgrade pip; pip install --requirement requirements.txt

      - name: Create archive
        run: tar -zcvf bytes_venv_${{ env.RELEASE_VERSION }}.tar.gz -C /var/www/html/ .venv

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: bytes_venv_${{ env.RELEASE_VERSION }}
          path: bytes_venv_${{ env.RELEASE_VERSION }}.tar.gz

