name: package boefjes for debian

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: Version number
        required: true

jobs:
  build_deb:

    runs-on: ubuntu-20.04
    env:
      PKG_NAME: kat-boefjes
      BUILD_DIR: /tmp/pkg_build

    steps:
      - name: Set env
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

          if [ -z "${{ inputs.version }}" ]; then
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v1

      - name: Replace version number with release version
        run: find . -type f -name 'version.py' -exec sed -ibak "s/__version__ = .*/__version__ = \"${RELEASE_TAG}\"/" {} \;

      - name: Clone octopoes
        run: git clone https://${{ secrets.RDO_REPO_RO }}@github.com/minvws/nl-rt-tim-abang-octopoes.git /tmp/octopoes

      - name: Run Debian package build script
        run: packaging/scripts/build-debian-package.sh
        env:
          REPOSITORY: ${{ github.repository }}
          OCTOPOES_DIR: /tmp/octopoes

      - name: Upload .deb to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kat-boefjes_${{ env.RELEASE_VERSION }}.deb
          path: ${{ BUILD_DIR }}/kat-boefjes_${{ env.RELEASE_VERSION }}_all.deb
