name: Keiko Check the LaTeX style using linters

on:
  push:
    paths:
      - keiko/**
  pull_request:
    paths:
      - keiko/**

jobs:
  check-latex:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install chktex
        run: sudo apt-get install chktex

      - name: Run checks
        run: make check-latex
        working-directory: ./keiko
