name: Check if translations file is up to date

on:
  push:
    branches:
      - "main"
      - "release-*"
      - "v2"
    tags:
      - "*"
      - "!plugins-*"
  pull_request:

jobs:
  makelang:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install GNU gettext utilities
        run: sudo apt-get install -y --no-install-recommends gettext=0.23.1-2

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"

      - name: Install requirements and activate it
        run: uv sync

      - name: Generate the .pot file if source strings changed
        run: uv run make lang
        env:
          SECRET_KEY: none
          REDIS_QUEUE_URI: redis://localhost/fake
          REDIS_PASSWORD: fake
          REDIS_HOST: redis://localhost/fake

      - name: Check if at least one source string changed
        run: |
          changed_lines=$(git diff --unified=0 openkat/locale/django.pot | grep -E -o '^[+-](msgid|msgstr)' | wc -l)
          if [ "$changed_lines" -ge 1 ]; then
            echo "More than just POT-Creation-Date changed in django.pot"
            git diff --unified=0 openkat/locale/django.pot
            exit 1
          fi
