name: Mula Run the test suite

on:
  push:
    paths:
      - mula/**
  pull_request:
    paths:
      - mula/**

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: ['3.8', '3.9', '3.10', '3.11']

    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the images
        run: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f base.yml -f .ci/docker-compose.yml build --build-arg PYTHON_VERSION=${{ matrix.version }}
        working-directory: ./mula

      - name: Run unit tests
        run: make utest
        working-directory: ./mula

      - name: Run integration tests
        run: make itest
        working-directory: ./mula
