name: Build the plugin image(s)

on:
  push:
    branches:
      - "main"
      - "release-*"
      - "v2"
    tags:
      - "plugins/v*"
    paths:
      - plugins/plugins/**
      - .github/workflows/plugin_images.yml
  pull_request:
    paths:
      - plugins/plugins/**
      - .github/workflows/plugin_images.yml

jobs:
  build_plugin_images:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        id: buildx
        with:
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/openkat/plugins
          tags: |
            type=ref,event=branch,prefix=branch-
            type=semver,pattern=v{{version}},match=v(\d.\d.\d)$
            type=ref,event=pr

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image for openkat/plugins
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          # We don't use git context because that doesn't process .dockerignore
          # https://github.com/docker/cli/issues/2827
          file: plugins/plugins/plugins.Dockerfile
          push: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
