version: "3.9"

services:

  rabbitmq:
    restart: on-failure
    image: "rabbitmq:3.11-management"
    ports:
      - "127.0.0.1:28003:15672"
      - "127.0.0.1:28004:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      retries: 10
    env_file:
      - ".ci/ci-crux.env"

  crux:
    env_file:
      - ".ci/ci-crux.env"
    healthcheck:
      test: [ "CMD", "python3", "/home/health_check.py", "http://localhost:3000/_crux/status"]
      interval: 5s
      retries: 10
    image: "juxt/crux-in-memory:21.05-1.17.0"
    ports:
      - "127.0.0.1:28002:3000"
    restart: on-failure
    volumes:
      - ./.ci/health_check.py:/home/health_check.py

  octopoes_api:
    build:
      context: .
    command: uvicorn octopoes.api.api:app --host 0.0.0.0 --port 80
    depends_on:
      rabbitmq:
        condition: service_healthy
      crux:
        condition: service_healthy
    ports:
        - "127.0.0.1:28000:80"
    env_file:
      - ".ci/ci-crux.env"

  octopoes_api_worker:
    build:
      context: .
    command: celery -A octopoes.tasks.tasks worker -E -B -s /tmp/celerybeat-schedule --loglevel=INFO
    depends_on:
      rabbitmq:
        condition: service_healthy
      crux:
        condition: service_healthy
    env_file:
      - ".ci/ci-crux.env"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  katalogus_mock:
    image: "wiremock/wiremock:2.34.0"
    volumes:
      - ./.ci/wiremock:/home/wiremock
    ports:
      - "127.0.0.1:28001:8080"
    env_file:
      - ".ci/ci-crux.env"
